services:
  - type: static
    name: hutz-live-frontend
    env: static
    plan: free
    staticPublishPath: dist
    routes:
      # Rewrite específico para 404
      - type: rewrite
        src: '/404'
        dest: '/index.html'
      # Reescreve **todas** as outras URLs para /index.html  
      - type: rewrite
        src: '/.*'
        dest: '/index.html'
