services:
  - type: static
    name: hutz-live-frontend
    env: static
    plan: free
    staticPublishPath: dist           # ou ./build, conforme sua config de build
    routes:
      # Reescreve **todas** as URLs para /index.html
      - type: rewrite
        src: '/.*'
        dest: '/index.html'
