
[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "node index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=1024"

[staticAssets]
"/public" = "./public"
