
[build]
builder = "nixpacks"
buildCommand = "npm ci"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = { default = "8080" }
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=1024"

[networking]
externalPort = 8080
internalPort = 8080

[nixpacks]
configFile = "nixpacks.toml"
