// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vikhirqxfhmpgbkycwra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpa2hpcnF4ZmhtcGdia3ljd3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzQyMDAsImV4cCI6MjA1OTk1MDIwMH0.PdqE2b3irP0EDlcqb4ahOBxF5CKBflOCO_x_qPl8MAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);