// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuhvpzprzqdfcojueswo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aHZwenByenFkZmNvanVlc3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzYyMTcsImV4cCI6MjA2ODM1MjIxN30.EOxuKRd31gvZtp-WXNtR5luwiVyNMbn1X-bGIz9TVgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);